# Site settings
title: "CopperPeakLimited"
email: "copperpeakltd@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://copperpeakltd.co.uk" # the base hostname & protocol for your site

twitter_username:
linkedin_username:

# Build settings
markdown: kramdown
